# The name of the workflow
name: Deploy Frontend to GitHub Pages

# Run this workflow every time a change is pushed to the 'main' branch
# also allows you to run it manually from the Actions tab
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

# Grant the necessary permissions for the workflow to deploy
permissions:
  contents: read
  pages: write
  id-token: write

# The deployment job
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configures GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Takes the contents of your /frontend folder and prepares it for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend'

      # Step 4: Deploys the prepared content to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
